// 002:T021 One sharing image per language, generated by the build (002:FR-011)
import type { APIRoute, GetStaticPaths } from 'astro';
import { locales, type Locale } from '../../i18n/ui.ts';
import { renderOgImage } from '../../site/og-image.ts';

export const getStaticPaths = (() =>
  locales.map((locale) => ({ params: { locale } }))) satisfies GetStaticPaths;

export const GET: APIRoute = async ({ params }) => {
  const png = await renderOgImage(params['locale'] as Locale);
  return new Response(png, { headers: { 'Content-Type': 'image/png' } });
};
